import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { log } from "../log.js";

export const AGENTS_HELP = `siteforge agents — write conventions for AI agents working in this repo.

Usage:
  siteforge agents            Print detected stack (commands included with --json)
  siteforge agents init [--force]

Detects the stack from package.json + lockfiles + configs and writes
AGENTS.md: how to install, run, test, lint, and build — plus working
agreements (TypeScript strict, mobile-first, conventional commits).
Agents (and humans) read it to get productive in seconds.
`;

export interface StackInfo {
  name: string;
  pm: string | null;
  scripts: Record<string, string>;
  frameworks: string[];
  styling: string[];
  testing: string[];
  typescript: boolean;
  strict: boolean;
}

function readJson(file: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(file, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/** Detect stack signals from the current directory. Pure-ish and tested. */
export function detectStack(cwd: string = process.cwd()): StackInfo {
  const pkg = readJson(path.join(cwd, "package.json")) ?? {};
  const deps = {
    ...((pkg.dependencies ?? {}) as Record<string, string>),
    ...((pkg.devDependencies ?? {}) as Record<string, string>),
  };
  const has = (...names: string[]) => names.some((n) => n in deps);
  const file = (f: string) => existsSync(path.join(cwd, f));

  let pm: string | null = null;
  if (file("bun.lock")) pm = "bun";
  else if (file("pnpm-lock.yaml")) pm = "pnpm";
  else if (file("package-lock.json")) pm = "npm";
  else if (file("yarn.lock")) pm = "yarn";

  const frameworks: string[] = [];
  if (has("next")) frameworks.push("Next.js " + (deps.next ?? ""));
  if (has("astro")) frameworks.push("Astro");
  if (has("vite")) frameworks.push("Vite");
  if (has("react") && !has("next")) frameworks.push("React");
  if (has("express", "fastify", "hono")) frameworks.push("Node API");

  const styling: string[] = [];
  if (has("tailwindcss")) styling.push("Tailwind CSS");
  if (has("three")) styling.push("Three.js");

  const testing: string[] = [];
  if (has("vitest")) testing.push("Vitest");
  if (has("jest")) testing.push("Jest");
  if (has("playwright", "playwright-core", "@playwright/test")) testing.push("Playwright");

  const tsconfig = readJson(path.join(cwd, "tsconfig.json"));
  const strict =
    (tsconfig?.compilerOptions as Record<string, unknown> | undefined)?.strict === true;

  return {
    name: String(pkg.name ?? path.basename(path.resolve(cwd))),
    pm,
    scripts: (pkg.scripts ?? {}) as Record<string, string>,
    frameworks,
    styling,
    testing,
    typescript: file("tsconfig.json"),
    strict,
  };
}

export function renderAgentsMd(info: StackInfo): string {
  const run = (script: string) => {
    if (!info.scripts[script]) return null;
    const base = info.pm === "npm" ? "npm run" : info.pm === "pnpm" ? "pnpm" : info.pm === "yarn" ? "yarn" : "bun run";
    return `${base} ${script}`;
  };
  const cmd = (script: string) => run(script) ?? "";
  const body = [
    `# AGENTS.md — ${info.name}`,
    ``,
    `Conventions for AI agents (and humans) working in this repo. Generated by \`siteforge agents init\` — edit freely.`,
    ``,
    `## Stack`,
    ``,
    ...info.frameworks.map((f) => `- ${f}`),
    ...info.styling.map((f) => `- ${f}`),
    ...info.testing.map((f) => `- ${f}`),
    ...(info.typescript ? [`- TypeScript${info.strict ? " (strict)" : ""}`] : []),
    ...(info.pm ? [`- Package manager: ${info.pm}`] : []),
    ``,
    `## Commands`,
    ``,
    `- Install: \`${info.pm === "npm" ? "npm install" : info.pm ? `${info.pm} install` : "npm install"}\``,
    ...(info.scripts.dev ? [`- Dev: \`${cmd("dev")}\``] : []),
    ...(info.scripts.build ? [`- Build: \`${cmd("build")}\``] : []),
    ...(info.scripts.test ? [`- Test: \`${cmd("test")}\``] : []),
    ...(info.scripts.lint ? [`- Lint: \`${cmd("lint")}\``] : []),
    ...(info.scripts.check ? [`- Typecheck: \`${cmd("check")}\``] : []),
    ``,
    `## Agreements`,
    ``,
    `- Mobile-first: verify at 375px; fluid type with \`clamp()\`; no fixed widths past the viewport.`,
    `- TypeScript strict where enabled — no implicit any, no unused locals.`,
    `- Verify with the real command (build/tests), never by reasoning alone.`,
    `- Small, reviewable diffs. Conventional commits (\`feat:\`, \`fix:\`, \`docs:\`, \`chore:\`).`,
    `- Never commit secrets, lockfiles from other managers, or build output.`,
    ``,
  ];
  return body.join("\n");
}

export function parseAgentsArgs(argv: string[]): { init: boolean; force: boolean } {
  let init = false, force = false;
  for (const a of argv) {
    if (a === "init") init = true;
    else if (a === "--force") force = true;
    else throw new Error(`Unknown argument for agents: ${a} (usage: siteforge agents [init] [--force])`);
  }
  return { init, force };
}

export async function runAgents(o: { init: boolean; force: boolean; cwd?: string }): Promise<{ stack: StackInfo; wrote?: string }> {
  const cwd = o.cwd ?? process.cwd();
  const info = detectStack(cwd);
  if (!o.init) {
    log.step(`Stack for ${info.name}:`);
    for (const f of [...info.frameworks, ...info.styling, ...info.testing]) log.dim(`  - ${f}`);
    log.dim(`  pm: ${info.pm ?? "unknown"} · ts: ${info.typescript ? (info.strict ? "strict" : "loose") : "no"}`);
    log.blank();
    log.dim("  Write AGENTS.md: siteforge agents init");
    return { stack: info };
  }
  const target = path.join(cwd, "AGENTS.md");
  if (existsSync(target) && !o.force) {
    throw new Error("AGENTS.md already exists — pass --force to overwrite.");
  }
  writeFileSync(target, renderAgentsMd(info));
  log.ok(`Wrote ${target}`);
  return { stack: info, wrote: target };
}
